### ISSUE TITLE
Server Error: onchange() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by iiram** [ventor-tech/merp#101]
Why am I getting this type of errors on mobile? Almost anything I try to do with the mobile app ends up with this kind of an error - mismatch with the positional arguments.

**Comment by okuryan** [comment]
@iiram , could you, please, add exact steps to reproduce and screenshots of error.
Also, try to do the same actions in Odoo web interface. This is server error. So most likely proplem also reproducible on Odoo web interface and can be related to custom modules that can be installed on your system

**Comment by okuryan** [comment]
CLosing that issue due to inactivity
